backend:
  name: git-gateway
  branch: main

locale: 'fr'

media_folder: public/images/blog
public_folder: /images/blog

collections:
  - name: 'blog'
    label: 'Articles de Blog'
    folder: 'src/content/blog'
    create: true
    slug: '{{slug}}'
    extension: md
    format: frontmatter
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Date de publication', name: 'publishDate', widget: 'datetime' }
      - { label: 'Auteur', name: 'author', widget: 'string', default: 'Benjamin' }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
